More user-friendly error message if node-gyp is missing

diff --git a/npm/private/lifecycle/min/node-gyp-bin/node-gyp b/npm/private/lifecycle/min/node-gyp-bin/node-gyp
--- a/npm/private/lifecycle/min/node-gyp-bin/node-gyp
+++ b/npm/private/lifecycle/min/node-gyp-bin/node-gyp
@@ -1,6 +1,12 @@
 #!/usr/bin/env sh
-export npm_globals="$(npm list -g | head -1)"
-node "$npm_globals/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "$@"
+npm_globals="$(npm list -g | head -1)"
+node_gyp_script="$npm_globals/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js"
+if test -f "$node_gyp_script"; then
+  node "$npm_globals/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "$@"
+else
+  echo "Could not locate node-gyp. Please install it globally by running: npm i -g node-gyp"
+  exit 1
+fi
 #if [ "x$npm_config_node_gyp" = "x" ]; then
 #  node "`dirname "$0"`/../../node_modules/node-gyp/bin/node-gyp.js" "$@"
 #else
